/**
 * Named particle effects: one or more emitter rows (Darkplaces-style fields).
 * Distances are meters. Quake/DP values were divided by 32.
 */

const U = 1 / 32;
const q = (n) => n * U;

const row = (o) => ({
  count: 32,
  rate: 1,
  color: 0xffffff,
  additive: false,
  life: [0.6, 1.1],
  size: 0.3,
  sizeincrease: 0,
  originoffset: [0, 0, 0],
  originjitter: [0, 0, 0],
  velocityoffset: [0, 0, 0],
  velocityjitter: [0, 0, 0],
  velocitymultiplier: 1,
  gravity: 0,
  airfriction: 0,
  bounce: 0,
  slide: false,
  wind: 0,
  orientation: 'billboard',
  burst: false,
  retrigger: 0,
  ...o,
});

const fire = row({
  count: 40,
  color: 0xff7a1a,
  additive: true,
  life: [0.5, 1.05],
  size: 0.4,
  sizeincrease: 1.45,
  originjitter: [0.15, 0.04, 0.15],
  velocityoffset: [0, 0.85, 0],
  velocityjitter: [0.22, 0.52, 0.22],
  wind: 1,
});

const smoke = row({
  count: 36,
  color: 0x7a7a7a,
  life: [1.5, 2.8],
  size: 0.55,
  sizeincrease: 2.05,
  originoffset: [0, 0.35, 0],
  originjitter: [0.14, 0, 0.14],
  velocityoffset: [0, 0.55, 0],
  velocityjitter: [0.2, 0.25, 0.2],
  gravity: -0.04,
  airfriction: 0.6,
  bounce: 0.15,
  slide: true,
  wind: 1,
});

const sparks = row({
  count: 50,
  color: 0xffcc55,
  additive: true,
  life: [0.25, 0.7],
  size: 0.07,
  sizeincrease: -0.03,
  originoffset: [0, 0.2, 0],
  originjitter: [0.1, 0, 0.1],
  velocityoffset: [0, 4, 0],
  velocityjitter: [4, 2, 4],
  gravity: 0.67,
  bounce: 0.55,
  orientation: 'spark',
  wind: 0.4,
});

const spray = row({
  count: 70,
  color: 0xc8e8ff,
  life: [0.4, 0.9],
  size: 0.08,
  sizeincrease: 0.06,
  originjitter: [0.06, 0, 0.06],
  velocityoffset: [0, 4.2, 0],
  velocityjitter: [0.6, 0.75, 0.6],
  gravity: 0.5,
  bounce: -1,
});

const dust = row({
  count: 48,
  color: 0xc4a574,
  life: [0.45, 0.95],
  size: 0.32,
  sizeincrease: 1.03,
  originjitter: [0.09, 0, 0.09],
  velocityoffset: [0, 0.5, 0],
  velocityjitter: [0.7, 0.32, 0.7],
  gravity: 0.04,
  airfriction: 1.4,
});

const wake = row({
  count: 64,
  color: 0xe8f4ff,
  additive: true,
  life: [0.35, 0.8],
  size: 0.1,
  sizeincrease: 0.38,
  originjitter: [0.08, 0, 0.08],
  velocityoffset: [0, 1.2, 0],
  velocityjitter: [1.6, 0.9, 1.6],
  gravity: 0.44,
});

export const EFFECTS = {
  fire: [fire],
  smoke: [smoke],
  sparks: [sparks],
  spray: [spray],
  dust: [dust],
  wake: [wake],
  campfire: [fire, smoke, sparks],
  bubble: [
    row({
      count: 28,
      color: 0xa8c8e0,
      life: [1.2, 2.4],
      size: 0.06,
      sizeincrease: 0.08,
      originjitter: [0.12, 0.05, 0.12],
      velocityoffset: [0, 0.45, 0],
      velocityjitter: [0.12, 0.2, 0.12],
      gravity: -0.12,
      bounce: 0.1,
    }),
  ],
  TE_GUNSHOT: [
    row({
      count: 8,
      rate: 0,
      burst: true,
      retrigger: 0.9,
      color: 0x505050,
      life: [0.35, 0.7],
      size: q(5),
      sizeincrease: q(2),
      originjitter: [q(2), q(2), q(2)],
      velocityjitter: [q(8), q(8), q(8)],
      gravity: -0.05,
      airfriction: 0.8,
    }),
    row({
      count: 12,
      rate: 0,
      burst: true,
      retrigger: 0.9,
      color: 0xffab57,
      additive: true,
      life: [0.2, 0.45],
      size: q(2),
      originjitter: [q(2), q(2), q(2)],
      velocityjitter: [q(48), q(48), q(48)],
      gravity: 1,
      bounce: 0.5,
      orientation: 'spark',
    }),
  ],
  TE_SPIKE: [
    row({
      count: 10,
      rate: 0,
      burst: true,
      retrigger: 0.7,
      color: 0xffd080,
      additive: true,
      life: [0.2, 0.5],
      size: q(2),
      velocityjitter: [q(64), q(64), q(64)],
      gravity: 1,
      bounce: 0.6,
      orientation: 'spark',
    }),
  ],
  TE_SUPERSPIKE: [
    row({
      count: 18,
      rate: 0,
      burst: true,
      retrigger: 0.7,
      color: 0xffe8a0,
      additive: true,
      life: [0.25, 0.55],
      size: q(2.5),
      velocityjitter: [q(96), q(96), q(96)],
      gravity: 1,
      bounce: 0.65,
      orientation: 'spark',
    }),
  ],
  TE_WIZSPIKE: [
    row({
      count: 14,
      rate: 0,
      burst: true,
      retrigger: 0.8,
      color: 0x6fff00,
      additive: true,
      life: [0.3, 0.7],
      size: q(6),
      sizeincrease: q(2),
      originjitter: [q(8), q(8), q(8)],
      velocityjitter: [q(32), q(32), q(32)],
      gravity: 1,
      bounce: 1,
    }),
  ],
  TE_KNIGHTSPIKE: [
    row({
      count: 12,
      rate: 0,
      burst: true,
      retrigger: 0.75,
      color: 0xff8020,
      additive: true,
      life: [0.25, 0.55],
      size: q(3),
      velocityjitter: [q(48), q(48), q(48)],
      gravity: 1,
      bounce: 0.8,
      orientation: 'spark',
    }),
  ],
  TE_EXPLOSION: [
    row({
      count: 24,
      rate: 0,
      burst: true,
      retrigger: 2.4,
      color: 0xffd080,
      additive: true,
      life: [0.45, 0.9],
      size: q(16),
      originjitter: [q(8), q(8), q(8)],
      velocityjitter: [q(96), q(96), q(96)],
      gravity: 0.2,
      airfriction: 1.2,
      bounce: 0.4,
    }),
    row({
      count: 16,
      rate: 0,
      burst: true,
      retrigger: 2.4,
      color: 0x303030,
      life: [0.8, 1.5],
      size: q(12),
      sizeincrease: q(8),
      originjitter: [q(8), q(8), q(8)],
      velocityjitter: [q(48), q(48), q(48)],
      gravity: -0.05,
      airfriction: 0.8,
    }),
    row({
      count: 20,
      rate: 0,
      burst: true,
      retrigger: 2.4,
      color: 0xffd030,
      additive: true,
      life: [0.35, 0.7],
      size: q(2),
      velocityoffset: [0, q(80), 0],
      velocityjitter: [q(256), q(256), q(256)],
      gravity: 1,
      bounce: 0.55,
      orientation: 'spark',
    }),
  ],
  TE_TAREXPLOSION: [
    row({
      count: 28,
      rate: 0,
      burst: true,
      retrigger: 2.6,
      color: 0x40ff40,
      additive: true,
      life: [0.5, 1],
      size: q(10),
      originjitter: [q(12), q(12), q(12)],
      velocityjitter: [q(80), q(80), q(80)],
      gravity: -0.08,
      airfriction: 0.5,
    }),
    row({
      count: 16,
      rate: 0,
      burst: true,
      retrigger: 2.6,
      color: 0xa0ffa0,
      additive: true,
      life: [0.3, 0.6],
      size: q(2),
      velocityjitter: [q(160), q(160), q(160)],
      gravity: 0.8,
      bounce: 0.5,
      orientation: 'spark',
    }),
  ],
  TE_TELEPORT: [
    row({
      count: 40,
      rate: 0,
      burst: true,
      retrigger: 2.2,
      color: 0xd0d0ff,
      additive: true,
      life: [0.5, 1],
      size: q(10),
      originoffset: [0, q(28), 0],
      originjitter: [q(16), q(28), q(16)],
      velocityjitter: [0, q(256), 0],
      airfriction: 1,
    }),
  ],
  TE_LAVASPLASH: [
    row({
      count: 32,
      rate: 0,
      burst: true,
      retrigger: 2.2,
      color: 0xe3974f,
      additive: true,
      life: [0.7, 1.3],
      size: q(12),
      originoffset: [0, q(32), 0],
      originjitter: [q(48), q(16), q(48)],
      velocityoffset: [0, q(120), 0],
      velocityjitter: [q(64), 0, q(64)],
      gravity: 0.05,
    }),
  ],
  TE_SPARK: [
    row({
      count: 20,
      rate: 0,
      burst: true,
      retrigger: 0.6,
      color: 0xffcc44,
      additive: true,
      life: [0.2, 0.5],
      size: q(2),
      velocityjitter: [q(96), q(96), q(96)],
      gravity: 1,
      bounce: 0.7,
      orientation: 'spark',
    }),
  ],
  TE_PLASMABURN: [
    row({
      count: 16,
      rate: 0,
      burst: true,
      retrigger: 1.1,
      color: 0x80ffff,
      additive: true,
      life: [0.25, 0.5],
      size: q(6),
      sizeincrease: q(-2),
      originjitter: [q(4), q(4), q(4)],
      velocityjitter: [q(24), q(24), q(24)],
      airfriction: 2,
    }),
  ],
  TE_FLAMEJET: [
    row({
      count: 36,
      color: 0xe3974f,
      additive: true,
      life: [0.4, 0.9],
      size: q(4),
      velocityjitter: [q(48), q(48), q(48)],
      velocitymultiplier: 1,
      gravity: -0.35,
      airfriction: 1,
      bounce: 0.2,
      wind: 0.8,
    }),
  ],
  TE_TEI_SMOKE: [
    row({
      count: 24,
      color: 0x888888,
      life: [0.8, 1.6],
      size: q(8),
      sizeincrease: q(6),
      originjitter: [q(4), q(4), q(4)],
      velocityjitter: [q(16), q(16), q(16)],
      gravity: -0.06,
      airfriction: 0.7,
      wind: 1,
    }),
  ],
  TE_TEI_BIGEXPLOSION: [
    row({
      count: 32,
      rate: 0,
      burst: true,
      retrigger: 2.8,
      color: 0xff8020,
      additive: true,
      life: [0.5, 1],
      size: q(20),
      originjitter: [q(16), q(16), q(16)],
      velocityjitter: [q(128), q(128), q(128)],
      gravity: 0.15,
      airfriction: 1,
    }),
    row({
      count: 20,
      rate: 0,
      burst: true,
      retrigger: 2.8,
      color: 0x222222,
      life: [1, 1.8],
      size: q(16),
      sizeincrease: q(12),
      velocityjitter: [q(40), q(40), q(40)],
      gravity: -0.04,
    }),
  ],
  TE_TEI_PLASMAHIT: [
    row({
      count: 18,
      rate: 0,
      burst: true,
      retrigger: 1.0,
      color: 0x40c0ff,
      additive: true,
      life: [0.2, 0.45],
      size: q(4),
      velocityjitter: [q(80), q(80), q(80)],
      gravity: 0.3,
      bounce: 0.4,
      orientation: 'spark',
    }),
  ],
  EF_FLAME: [
    row({
      count: 32,
      color: 0xff6010,
      additive: true,
      life: [0.4, 0.85],
      size: q(5),
      sizeincrease: q(3),
      originjitter: [q(6), q(4), q(6)],
      velocityoffset: [0, q(24), 0],
      velocityjitter: [q(12), q(16), q(12)],
      gravity: -0.2,
      wind: 1,
    }),
  ],
  EF_STARDUST: [
    row({
      count: 40,
      color: 0xffffc0,
      additive: true,
      life: [0.8, 1.6],
      size: q(2),
      originjitter: [q(24), q(24), q(24)],
      velocityjitter: [q(8), q(8), q(8)],
      gravity: 0.15,
    }),
  ],
  TR_ROCKET: [
    row({
      count: 28,
      color: 0x555555,
      life: [0.5, 0.9],
      size: q(3.5),
      sizeincrease: q(8),
      originjitter: [q(2), q(2), q(2)],
      velocityoffset: [0, q(40), 0],
      velocityjitter: [q(8), q(8), q(8)],
      gravity: -0.02,
      airfriction: 0.4,
    }),
    row({
      count: 20,
      color: 0xffdf72,
      additive: true,
      life: [0.25, 0.5],
      size: q(5),
      originjitter: [q(2), q(2), q(2)],
      velocityoffset: [0, q(32), 0],
      velocityjitter: [q(16), q(16), q(16)],
    }),
  ],
  TR_GRENADE: [
    row({
      count: 24,
      color: 0x666666,
      life: [0.4, 0.8],
      size: q(3),
      sizeincrease: q(4),
      originjitter: [q(2), q(2), q(2)],
      velocityoffset: [0, q(20), 0],
      velocityjitter: [q(12), q(12), q(12)],
      gravity: 0.1,
    }),
  ],
  TR_WIZSPIKE: [
    row({
      count: 22,
      color: 0x80ff40,
      additive: true,
      life: [0.3, 0.6],
      size: q(3),
      originjitter: [q(3), q(3), q(3)],
      velocityoffset: [0, q(24), 0],
      velocityjitter: [q(20), q(20), q(20)],
    }),
  ],
  TR_KNIGHTSPIKE: [
    row({
      count: 22,
      color: 0xffa040,
      additive: true,
      life: [0.3, 0.6],
      size: q(3),
      originjitter: [q(3), q(3), q(3)],
      velocityoffset: [0, q(24), 0],
      velocityjitter: [q(20), q(20), q(20)],
    }),
  ],
  TR_VORESPIKE: [
    row({
      count: 22,
      color: 0xc040ff,
      additive: true,
      life: [0.3, 0.65],
      size: q(3.5),
      originjitter: [q(4), q(4), q(4)],
      velocityoffset: [0, q(20), 0],
      velocityjitter: [q(24), q(24), q(24)],
      gravity: -0.05,
    }),
  ],
  TR_NEHAHRASMOKE: [
    row({
      count: 30,
      color: 0x9a9a9a,
      life: [1.2, 2.2],
      size: q(6),
      sizeincrease: q(10),
      originjitter: [q(4), q(2), q(4)],
      velocityoffset: [0, q(18), 0],
      velocityjitter: [q(10), q(8), q(10)],
      gravity: -0.08,
      airfriction: 0.9,
      wind: 1,
    }),
  ],
  TR_GLOWTRAIL: [
    row({
      count: 24,
      color: 0xa0e8ff,
      additive: true,
      life: [0.35, 0.7],
      size: q(4),
      sizeincrease: q(-1),
      originjitter: [q(2), q(2), q(2)],
      velocityoffset: [0, q(16), 0],
      velocityjitter: [q(8), q(8), q(8)],
    }),
  ],
};

export const effectNames = () => Object.keys(EFFECTS);
